// Shows the value of every input on screen, to check what the shaders
// receive. Numbers use a small 3x5 pixel font; the labels are packed into
// integers (6 bits per character), generated by a script.

// Characters: 0-9 are codes 0-9, A-Z are 10-35, then '.', '-' and space.
// Each glyph is 5 rows of 3 pixels, top row in the high bits.
const FONT = array<u32, 39>(
    0x7b6fu, 0x2c97u, 0x73e7u, 0x73cfu, 0x5bc9u, 0x79cfu, 0x79efu, 0x7249u,
    0x7befu, 0x7bcfu, 0x2bedu, 0x6baeu, 0x3923u, 0x6b6eu, 0x79a7u, 0x79a4u,
    0x396bu, 0x5bedu, 0x7497u, 0x126au, 0x5badu, 0x4927u, 0x5fedu, 0x6b6du,
    0x2b6au, 0x6ba4u, 0x2b73u, 0x6badu, 0x388eu, 0x7492u, 0x5b6fu, 0x5b6au,
    0x5bfdu, 0x5aadu, 0x5a92u, 0x72a7u, 0x0002u, 0x01c0u, 0x0000u
);
const DOT: u32 = 36u;
const MINUS: u32 = 37u;

const INK = vec3<f32>(0.92, 0.92, 0.95);
const DIM = vec3<f32>(0.35, 0.37, 0.42);
// Width of everything, in font pixels.
const WIDTH: i32 = 128;
// Length of the value bars, in font pixels.
const BAR: i32 = 64;

// Whether font pixel `cell` (column 0-2, row 0-4) of a character is lit.
fn glyph(code: u32, cell: vec2<i32>) -> bool {
    let bit = 14 - (cell.y * 3 + cell.x);
    return ((FONT[min(code, 38u)] >> u32(bit)) & 1u) == 1u;
}

// Whether `fp` is on character `index` drawn at `origin`, from its code.
fn character_cell(fp: vec2<i32>, origin: vec2<i32>) -> vec3<i32> {
    let rel = fp - origin;
    if rel.x < 0 || rel.y < 0 || rel.y >= 5 || rel.x % 4 == 3 {
        return vec3<i32>(-1);
    }
    return vec3<i32>(rel.x / 4, rel.x % 4, rel.y);
}

// A label of up to 10 characters, packed in `a` and `b`.
fn text(fp: vec2<i32>, origin: vec2<i32>, a: u32, b: u32, len: u32) -> bool {
    let cell = character_cell(fp, origin);
    if cell.x < 0 || u32(cell.x) >= len {
        return false;
    }
    let i = u32(cell.x);
    let word = select(b, a, i < 5u);
    let code = (word >> (6u * (i % 5u))) & 63u;
    return glyph(code, cell.yz);
}

fn pow10(k: u32) -> u32 {
    var result = 1u;
    for (var i = 0u; i < k; i++) {
        result *= 10u;
    }
    return result;
}

// A number with `decimals` digits after the point, e.g. -12.34.
fn number(fp: vec2<i32>, origin: vec2<i32>, value: f32, decimals: u32) -> bool {
    let cell = character_cell(fp, origin);
    if cell.x < 0 {
        return false;
    }
    let scale = f32(pow10(decimals));
    let rounded = round(abs(value) * scale);
    let whole = u32(floor(rounded / scale));
    let fraction = u32(rounded - f32(whole) * scale);
    var whole_len = 1u;
    while whole >= pow10(whole_len) && whole_len < 9u {
        whole_len += 1u;
    }
    let sign_len = select(0u, 1u, value < 0.0 && rounded > 0.0);
    let point_len = select(0u, 1u + decimals, decimals > 0u);
    let i = u32(cell.x);
    if i >= sign_len + whole_len + point_len {
        return false;
    }
    var code = MINUS;
    if i >= sign_len && i < sign_len + whole_len {
        code = (whole / pow10(whole_len - 1u - (i - sign_len))) % 10u;
    } else if i == sign_len + whole_len {
        code = DOT;
    } else if i > sign_len + whole_len {
        code = (fraction / pow10(decimals - (i - sign_len - whole_len))) % 10u;
    }
    return glyph(code, cell.yz);
}

// One "LABEL  0.42  [bar]" row; alpha 0 where nothing is drawn.
fn value_row(fp: vec2<i32>, y: i32, a: u32, b: u32, len: u32, value: f32, tint: vec3<f32>) -> vec4<f32> {
    if fp.y < y || fp.y >= y + 5 {
        return vec4<f32>(0.0);
    }
    if text(fp, vec2<i32>(0, y), a, b, len) || number(fp, vec2<i32>(40, y), value, 2u) {
        return vec4<f32>(INK, 1.0);
    }
    let x = fp.x - (WIDTH - BAR);
    if x >= 0 && x < BAR {
        let filled = f32(x) < clamp(value, 0.0, 1.0) * f32(BAR);
        return vec4<f32>(select(tint * 0.15, tint, filled), 1.0);
    }
    return vec4<f32>(0.0);
}

fn max_alpha(a: vec4<f32>, b: vec4<f32>) -> vec4<f32> {
    return select(a, b, b.a > a.a);
}

// A strip of 128 cells (MIDI notes or controllers), brighter with the value,
// with a tick under every C (notes 0, 12, 24... 60 is middle C).
fn strip(fp: vec2<i32>, y: i32, value: f32, tint: vec3<f32>) -> vec4<f32> {
    let i = fp.x;
    if i < 0 || i >= 128 {
        return vec4<f32>(0.0);
    }
    if fp.y >= y && fp.y < y + 6 {
        return vec4<f32>(mix(tint * 0.12, tint, clamp(value, 0.0, 1.0)), 1.0);
    }
    if fp.y == y + 7 && i % 12 == 0 {
        return vec4<f32>(DIM, 1.0);
    }
    return vec4<f32>(0.0);
}

@fragment
fn fs_main(@builtin(position) position: vec4<f32>) -> @location(0) vec4<f32> {
    // Font pixel size, and the block centered horizontally, below the controls.
    let size = max(2.0, floor(u.resolution.y / 200.0));
    let left = floor(0.5 * u.resolution.x - 0.5 * f32(WIDTH) * size);
    let fp = vec2<i32>(floor((position.xy - vec2<f32>(left, 80.0)) / size));
    var rows = vec4<f32>(0.0);

    // TIME (seconds) and RES (pixels)
    if text(fp, vec2<i32>(0, 0), 0x0039649du, 0x00000000u, 4u) || number(fp, vec2<i32>(40, 0), u.time, 2u)
        || text(fp, vec2<i32>(0, 8), 0x0001c39bu, 0x00000000u, 3u) || number(fp, vec2<i32>(40, 8), u.resolution.x, 0u)
        || text(fp, vec2<i32>(64, 8), 0x00000021u, 0x00000000u, 1u) || number(fp, vec2<i32>(72, 8), u.resolution.y, 0u) {
        rows = vec4<f32>(INK, 1.0);
    }

    // BEAT 
    rows = max_alpha(rows, value_row(fp, 16, 0x0074a38bu, 0x00000000u, 4u, u.beat, vec3<f32>(1.0, 0.55, 0.2)));
    // BASS 
    rows = max_alpha(rows, value_row(fp, 24, 0x0071c28bu, 0x00000000u, 4u, u.bass, vec3<f32>(0.3, 0.5, 1.0)));
    // MID 
    rows = max_alpha(rows, value_row(fp, 32, 0x0000d496u, 0x00000000u, 3u, u.mid, vec3<f32>(0.3, 0.9, 0.5)));
    // TREBLE 
    rows = max_alpha(rows, value_row(fp, 40, 0x152ce6ddu, 0x0000000eu, 6u, u.treble, vec3<f32>(1.0, 0.85, 0.3)));
    // PARAMS.X 
    rows = max_alpha(rows, value_row(fp, 48, 0x1629b299u, 0x0002191cu, 8u, u.params.x, vec3<f32>(0.8, 0.8, 0.8)));
    // PARAMS.Y 
    rows = max_alpha(rows, value_row(fp, 56, 0x1629b299u, 0x0002291cu, 8u, u.params.y, vec3<f32>(0.8, 0.8, 0.8)));
    // PARAMS.Z 
    rows = max_alpha(rows, value_row(fp, 64, 0x1629b299u, 0x0002391cu, 8u, u.params.z, vec3<f32>(0.8, 0.8, 0.8)));
    // PARAMS.W 
    rows = max_alpha(rows, value_row(fp, 72, 0x1629b299u, 0x0002091cu, 8u, u.params.w, vec3<f32>(0.8, 0.8, 0.8)));

    // BANDS: 64 bars, low frequencies on the left.
    if text(fp, vec2<i32>(0, 82), 0x1c35728bu, 0x031a5026u, 10u) {
        rows = vec4<f32>(INK, 1.0);
    }
    let chart_bottom = 90 + 40;
    if fp.x >= 0 && fp.x < WIDTH && fp.y >= 90 && fp.y < chart_bottom {
        let i = u32(fp.x / 2);
        let height = band(i) * 40.0;
        if fp.x % 2 == 0 && f32(chart_bottom - fp.y) <= height {
            rows = vec4<f32>(hue(0.66 * (1.0 - f32(i) / 63.0)), 1.0);
        } else if fp.y == chart_bottom - 1 {
            rows = vec4<f32>(DIM * 0.5, 1.0);
        }
    }

    // NOTES and CC: one cell per MIDI note / controller, 0 to 127.
    if text(fp, vec2<i32>(0, 136), 0x1c39d617u, 0x00000000u, 5u) || text(fp, vec2<i32>(0, 158), 0x0000030cu, 0x00000000u, 2u) {
        rows = vec4<f32>(INK, 1.0);
    }
    rows = max_alpha(rows, strip(fp, 144, note(u32(max(fp.x, 0))), vec3<f32>(1.0, 0.4, 0.6)));
    rows = max_alpha(rows, strip(fp, 166, cc(u32(max(fp.x, 0))), vec3<f32>(0.4, 0.9, 1.0)));

    let background = vec3<f32>(0.02, 0.02, 0.04);
    return vec4<f32>(mix(background, rows.rgb, rows.a), 1.0);
}
